name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --verbose

      - name: Build release
        run: cargo build --release --verbose

      - name: Test binary (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          ./target/release/gslc "\\P:A/P:B/S:AB\\"

      - name: Test binary (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          .\target\release\gslc.exe "\\P:A/P:B/S:AB\\"